import{S as d,i as l}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const g=document.querySelector(".feedback-form"),y=document.querySelector(".gallery");document.querySelector(".but-sub");const b="47413156-c8c9abea8f6d88937b7892740";let n,c;const w=new d(".gallery a",{captionDelay:250,captionsData:"alt"});g.addEventListener("submit",$);function $(s){s.preventDefault(),n=s.currentTarget.elements.photo.value.trim(),L(`${n}`),s.target.reset()}function L(s=""){if(s===""){l.show({color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=new URLSearchParams({key:b,q:`${n}`,image_type:"photo",orientation:"horizontal",safesearch:"true"});fetch(`https://pixabay.com/api/?${o}`).then(t=>{if(!t.ok)throw new Error(t.statusText);return t.json()}).then(t=>{if(!t.hits.length){l.show({color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}c=t.hits,console.log(c),y.insertAdjacentHTML("afterbegin",i(t.hits)),w.refresh()}).catch(t=>{console.log(t)}).finally(()=>console.log("ok"));function i(t){return t.map(({id:e,webformatURL:r,largeImageURL:a,tags:u,likes:h,views:p,comments:f,downloads:m})=>`<li data-id="${e}" class="gallery-item">
            <a href=${a} class="gallery-link">
            <img src=${r} class="gallery-image" alt=${u}> 
            <div class="wrap"><h2 class="title-like">Likes <span class="span-text"> ${h} </span></h2>
             <h2 class="title-views">Views <span class="span-text"> ${p} </span></h2>
             <h2 class="title-comments">Comments <span class="span-text">${f}</span> </h2>
             <h2 class="title-downloads">Downloads <span class="span-text">${m} </span></h2></div>
</a>
            </li>`).join("")}}
//# sourceMappingURL=index.js.map
